#+title: Email mu4e

Rujukan utama di sini [[http://www.ict4g.net/adolfo/notes/2014/12/27/EmacsIMAP.html][Adolfo]]

* Bagaimana prosesnya
Untuk dapatkan idea bagaimana proses yang membolehkan bacaan dan penghantaran email ialah seperti dibawah:
1. Salinkan email dari server ke lokal. Ini dihasilkan melalui [[http://isync.sourceforge.net/][isync]] atau
   ~offlineimpa~. Disini gunakan ~isync~ dan isync boleh dipasang menggunakan ~Synaptic~
2. Letakkan indeks di email supaya mudah utk penyusunan dan pencarian. Terdapat
   banyak program yang boleh dipakai seperti ~notmuch~, ~mu~ atau ~mairix~. Disini [[http://www.djcbsoftware.nl/code/mu/][mu]] dipakai.
3. Baca email dihasilkan melalui program [[http://www.djcbsoftware.nl/code/mu/mu4e.html][mu4e]] iaitu program yang termasuk dibawah ~mu~.
4. Buat folder 'Maildir' kemudian 'gmail' sekiranya akaun ingin dinamakan gmail.
5. Berapa program perlu dipasang:

#+BEGIN_EXAMPLE
  sudo apt install gmime-3.0
  sudo apt install libxapian-dev
  sudo apt install texinfo texi2html
#+END_EXAMPLE

6. Sekiranya masalah untuk larikan ~./autogen.sh~ bila compile ~mu~, perlu pasang program:

#+BEGIN_EXAMPLE
  sudo install automake
  ## atau ##
  sudo apt-get install dh-autoreconf
#+END_EXAMPLE

- sudo apt install gnupg2 -y utk guna gpg2 encrypting
- gpg2 --list-keys utk list semua keys
- ~mbsync -c ~/.emacs.d/.mbsynrc gmail~ – utk download email di akaun ‘gmail’ atau ‘work’ sekiranya didaftarkan di mbsyncrc

7. Sebelum email boleh dibaca selepas dimuatturun, harus di indeks-kan
#+BEGIN_EXAMPLE
  mu index --maildir=~/Maildir
#+END_EXAMPLE


Sekiranya ingin menggunakan pelbagai akaun email, pelbagai SMTP servers juga diperlukan. Proses seperti dibawah:
1. Tulis email boleh gunakan mode tersedia cth mu4e.
2. Menghantar email menggunakan [[http://msmtp.sourceforge.net/][msmtp]] yang membolehkan penghantaran email melalui
   pelbagai SMTP server. Ini dapat dilaksanakan dengan memilih server yang diingini di "from".

Funksi-funksi yang dipakai:
1. Email akaun di sediakan oleh Gmail atau lain-lain provider.
2. =mbsync -a= akan membuat salinan email di server ke lokal komputer dengan menggunakan format  [[https://en.wikipedia.org/wiki/Maildir][Maildir]]
3. =mu index= untuk membuat indeks di salinan email komputer lokal
4. =mu4e= ialah pakej di emacs yang dipakai utk baca email melalui format ~maildir~
   menggunakan fungsi di =mu= untuk mencari email.
5. =message mode= di emacs dipakai utk menulis email yang kemudiannya dihantar ke
   =msmtp=. Salinan email yang ditulis akan disimpan di lokal komputer yang kemudiannya
   di "sync" ke server memlalui =mbsync -a=
6. =msmtp= akan menggatur sambungan ke SMTP server dan memilih server yang telah
   ditetapkan di "from" utk email-email yang akan dihantar.
7. Proses "sync" dan mengindekskan email dilaksanakan secara automatik kerana =mu4e=
   akan mengaktifkan =mbsync -a= dan =mu index= secara langsung di emacs tanpa perlu
   dilaksanakan secara manual.

* mbsync
Cara terbaik untuk pasang =mbsync= ialah dengan mengkompilasi sendiri dari GitHub di [[https://sourceforge.net/p/isync/isync/ci/master/tree/][sini]]. Selepas clone boleh larikan:

#+BEGIN_EXAMPLE
  ./autogen.sh
  ./configure
  make
  sudo make install
#+END_EXAMPLE

Untuk penerangan terperinci boleh baca di [[https://cestlaz.github.io/posts/using-emacs-39-mu4e/#.W1z-tN9fg1k][blog]] ini.

Sebelum masangan [[https://github.com/djcb/mu][mu]] untuk =mu4e=, program2 ini harus dipasang:

#+BEGIN_EXAMPLE
  $ sudo apt-get install libgmime-2.6-dev libxapian-dev

  # optional
  $ sudo apt-get install guile-2.0-dev html2text xdg-utils

  # optional: only needed for msg2pdf and mug (toy gtk+ frontend)
  $ sudo apt-get install libwebkit-dev
#+END_EXAMPLE

Penerangan ini diambil dari [[https://www.djcbsoftware.nl/code/mu/mu4e/Installation.html][sini]]. Selepas ini bolehlah memasang =mu= dari
[[https://github.com/djcb/mu][GitHub]]. Pemasangannya juga sama seperti mbsync di atas.

Untuk muatturn email larikan

#+BEGIN_EXAMPLE
  mbsync -c ~/.emacs.d/.mbsyncrc gmail  ;hanya untuk akaun gmail
  mbsync -a ;untuk muatturun semua akaun
#+END_EXAMPLE

* smtpmail dan starttls
Untuk hantar email, pakai =smtpmail=. Sebelum pakai smtpmail, harus pasang
=gnutls-bin= dengan ~sudo apt install gnutls-bin~. Program boleh dipasang dengan memuat turun di
[[ftp://ftp.opaopa.org/pub/elisp/][starttls]]. Kemudian pakai:

#+BEGIN_EXAMPLE
./configure
make
sudo make install
#+END_EXAMPLE

Untuk buang program =starttls= ikut cara ini

#+BEGIN_QUOTE
You can remove the program binaries and object files from the
source code directory by typing `make clean'.  To also remove the
files that `configure' created (so you can compile the package for
a different kind of computer), type `make distclean'.  There is
also a `make maintainer-clean' target, but that is intended mainly
for the package's developers.  If you use it, you may have to get
all sorts of other programs in order to regenerate files that came
with the distribution.
#+END_QUOTE

Aturcara utk smtpmail contohnya di [[https://gist.github.com/rwaweber/208fd02b7aeb6a37e831][sini]].

#+BEGIN_EXAMPLE
  (setq message-send-mail-function 'smtpmail-send-it
        starttls-use-gnutls t
        smtpmail-starttls-credentials
        '(("smtp.gmail.com" 587 nil nil))
        smtpmail-auth-credentials
        (expand-file-name "~/.authinfo.gpg")
        smtpmail-default-smtp-server "smtp.gmail.com"
        smtpmail-smtp-server "smtp.gmail.com"
        smtpmail-smtp-service 587
        smtpmail-debug-info t)
#+END_EXAMPLE

* Guna GPG utk mbsync password
Rujukan diambil dari [[http://www.macs.hw.ac.uk/~rs46/posts/2014-01-13-mu4e-email-client.html][R.Steward]]

Fail-fail =SSL development= diperlukan oelh ~mbsync~ utk SSL authentication. Biasanya
fail-fail ini sudah tersedia di Ubuntu tetapi sekiranya belum ada, sila pasang seperti ini:

#+BEGIN_SRC sh
  sudo apt-get install libssl-dev
#+END_SRC

Buat fail sementara =.mbsyncpass= dan tuliskan password disitu. Kemudian larikan
#+BEGIN_SRC sh
  gpg2 --output .mbsyncpass.gpg --symmetric .mbsyncpass
#+END_SRC
Ini akan menghasilkan encrypted fail =mbsyncpass.gpg=. Simpan fail tersebut ke
=~/.emacs.d= dan buang fail sementara =.mbsyncpass= tadi.

Buat fail sementara =.authinfo= dan masukkan informasi ini
#+BEGIN_EXAMPLE
  machine imap.gmail.com login MyAccountName@gmail.com port 993 password MYPASSWORD
  machine smtp.gmail.com login MyAccountName@gmail.com port 587 password MYPASSWORD
#+END_EXAMPLE
Tukar yang berkenaan cth ~MyAccountName~ dan ~MYPASSWORD~

Kemudian untuk meng-encypt fail
#+BEGIN_SRC sh
  gpg2 --output ~/.authinfo.gpg --symmetric ~/.authinfo
#+END_SRC
Akan menghasilkan encrypted fail =.authoinfo.gpg=. Fail sementara =.authoinfo= boleh dibuang

* Aturcara isync utk Gmail

1. Berikan kebenaran ke [[https://support.google.com/accounts/answer/6010255?hl=en][Less Secure Apps]]
2. Pasangkan certificates yang diperlukan
   #+BEGIN_SRC sh
     sudo apt-get install ca-certificates
   #+END_SRC
3. Atur fail =~/.mbsyncrc= yang diperlukan.

** Contoh 1
   #+BEGIN_EXAMPLE
     IMAPAccount gmail
     # Address to connect to
     Host imap.gmail.com
     User yourname@gmail.com
     #Pass ***************
     # To store the password in an encrypted file use PassCmd instead of Pass
     #PassCmd "gpg2 -q --for-your-eyes-only --no-tty -d ~/.mbsyncpass.gpg"
     #
     # Use SSL
     UseIMAPS yes
     # The following line should work. If get certificate errors, uncomment the two following lines and read the "Troubleshooting" section.
     CertificateFile /etc/ssl/certs/ca-certificates.crt
     #CertificateFile ~/.cert/imap.gmail.com.pem
     #CertificateFile ~/.cert/Equifax_Secure_CA.pem

     IMAPStore gmail-remote
     Account gmail

     MaildirStore gmail-local
     # The trailing "/" is important
     Path ~/mail/
     Inbox ~/mail/Inbox

     Channel gmail
     Master :gmail-remote:
     Slave :gmail-local:
     # Exclude everything under the internal [Gmail] folder, except the interesting folders
     Patterns * ![Gmail]* "[Gmail]/Sent Mail" "[Gmail]/Starred" "[Gmail]/All Mail"
     # Or include everything
     #Patterns *
     # Automatically create missing mailboxes, both locally and on the server
     Create Both
     # Save the synchronization state files in the relevant directory
     SyncState *
   #+END_EXAMPLE
** Contoh 2
Contoh lain utk fail =.mbysncrc=
   #+BEGIN_EXAMPLE
     # ACCOUNT INFORMATION
     IMAPAccount gmail
     Host imap.gmail.com
     User MYEMAIL@gmail.com
     PassCmd "security find-generic-password -s mbsync-gmail-password -w"
     # UseIMAPS yes
     # AuthMechs LOGIN
     AuthMechs PLAIN
     SSLType IMAPS
     # SSLVersions SSLv3
     CertificateFile /usr/local/etc/openssl/certs/gmail.crt
     CertificateFile /usr/local/etc/openssl/certs/google.crt
     CertificateFile /usr/local/etc/openssl/certs/Equifax.crt

     # THEN WE SPECIFY THE LOCAL AND REMOTE STORAGE
     # - THE REMOTE STORAGE IS WHERE WE GET THE MAIL FROM (E.G., THE
     #   SPECIFICATION OF AN IMAP ACCOUNT)
     # - THE LOCAL STORAGE IS WHERE WE STORE THE EMAIL ON OUR COMPUTER

     # REMOTE STORAGE (USE THE IMAP ACCOUNT SPECIFIED ABOVE)
     IMAPStore gmail-remote
     Account gmail

     # LOCAL STORAGE (CREATE DIRECTORIES with mkdir -p Maildir/gmail)
     MaildirStore gmail-local
     Path ~/Maildir/gmail/
     Inbox ~/Maildir/gmail/inbox

     # CONNECTIONS SPECIFY LINKS BETWEEN REMOTE AND LOCAL FOLDERS
     #
     # CONNECTIONS ARE SPECIFIED USING PATTERNS, WHICH MATCH REMOTE MAIl
     # FOLDERS. SOME COMMONLY USED PATTERS INCLUDE:
     #
     # 1 "*" TO MATCH EVERYTHING
     # 2 "!DIR" TO EXCLUDE "DIR"
     # 3 "DIR" TO MATCH DIR
     #
     # FOR INSTANCE IN THE SPECIFICATION BELOW:
     #
     # gmail-inbox gets the folder INBOX, ARCHIVE, and everything under "ARCHIVE*"
     # gmail-trash gets only the "[Gmail]/Trash" folder and stores it to the local "trash" folder

     Channel gmail-inbox
     Master :gmail-remote:
     Slave :gmail-local:
     Patterns "INBOX" "Arch*"
     Create Both
     Expunge Both
     SyncState *

     Channel gmail-trash
     Master :gmail-remote:"[Gmail]/Trash"
     Slave :gmail-local:trash
     Create Both
     Expunge Both
     SyncState *

     Channel gmail-sent
     Master :gmail-remote:"[Gmail]/Sent Mail"
     Slave :gmail-local:sent
     Create Both
     Expunge Both
     SyncState *

     # GROUPS PUT TOGETHER CHANNELS, SO THAT WE CAN INVOKE
     # MBSYNC ON A GROUP TO SYNC ALL CHANNELS
     #
     # FOR INSTANCE: "mbsync gmail" GETS MAIL FROM
     # "gmail-inbox", "gmail-sent", and "gmail-trash"
     #
     Group gmail
     Channel gmail-inbox
     Channel gmail-sent
     Channel gmail-trash
   #+END_EXAMPLE

4. Utk sync email di server tertentu melalui terminal contohnya "work"
   #+BEGIN_SRC sh
     mbsync -c ~/.emacs.d/.mbsyncrc work
   #+END_SRC
