#+title: Email mu4e

Rujukan utama di sini [[http://www.ict4g.net/adolfo/notes/2014/12/27/EmacsIMAP.html][Adolfo]]

* Bagaimana prosesnya
Untuk dapatkan idea bagaimana proses yang membolehkan bacaan dan penghantaran email ialah seperti dibawah:
1. Salinkan email dari server ke lokal. Ini dihasilkan melalui [[http://isync.sourceforge.net/][isync]] atau
   ~offlineimpa~. Disini gunakan ~isync~ dan isync boleh dipasang menggunakan ~Synaptic~
2. Letakkan indeks di email supaya mudah utk penyusunan dan pencarian. Terdapat
   banyak program yang boleh dipakai seperti ~notmuch~, ~mu~ atau ~mairix~. Disini [[http://www.djcbsoftware.nl/code/mu/][mu]] dipakai.
3. Baca email dihasilkan melalui program [[http://www.djcbsoftware.nl/code/mu/mu4e.html][mu4e]] iaitu program yang termasuk dibawah ~mu~.

Sekiranya ingin menggunakan pelbagai akaun email, pelbagai SMTP servers juga diperlukan. Proses seperti dibawah:
1. Tulis email boleh gunakan mode tersedia cth mu4e.
2. Menghantar email menggunakan [[http://msmtp.sourceforge.net/][msmtp]] yang membolehkan penghantaran email melalui
   pelbagai SMTP server. Ini dapat dilaksanakan dengan memilih server yang diingini di "from".

Funksi-funksi yang dipakai:
1. Email akaun di sediakan oleh Gmail atau lain-lain provider.
2. =mbsync -a= akan membuat salinan email di server ke lokal komputer dengan menggunakan format  [[https://en.wikipedia.org/wiki/Maildir][Maildir]]
3. =mu index= untuk membuat indeks di salinan email komputer lokal
4. =mu4e= ialah pakej di emacs yang dipakai utk baca email melalui format ~maildir~
   menggunakan fungsi di =mu= untuk mencari email.
5. =message mode= di emacs dipakai utk menulis email yang kemudiannya dihantar ke
   =msmtp=. Salinan email yang ditulis akan disimpan di lokal komputer yang kemudiannya
   di "sync" ke server memlalui =mbsync -a=
6. =msmtp= akan menggatur sambungan ke SMTP server dan memilih server yang telah
   ditetapkan di "from" utk email-email yang akan dihantar.
7. Proses "sync" dan mengindekskan email dilaksanakan secara automatik kerana =mu4e=
   akan mengaktifkan =mbsync -a= dan =mu index= secara langsung di emacs tanpa perlu
   dilaksanakan secara manual.

* mbsync

Pasang =isync= yang juga memberikan pakej =mbsync=. Selain itu =maildir= dan =msmtp= juga perlu dipasang

#+BEGIN_SRC sh
  sudo apt-get install isync
  sudo apt-get install maildir-utils
  sudo apt-get install msmtp
#+END_SRC
* Guna GPG utk mbsync password
Rujukan diambil dari [[http://www.macs.hw.ac.uk/~rs46/posts/2014-01-13-mu4e-email-client.html][R.Steward]]

Fail-fail =SSL development= diperlukan oelh ~mbsync~ utk SSL authentication. Biasanya
fail-fail ini sudah tersedia di Ubuntu tetapi sekiranya belum ada, sila pasang seperti ini:

#+BEGIN_SRC sh
  sudo apt-get install libssl-dev
#+END_SRC

Buat fail sementara =.mbsyncpass= dan tuliskan password disitu. Kemudian larikan
#+BEGIN_SRC sh
  gpg2 --output .mbsyncpass.gpg --symmetric .mbsyncpass
#+END_SRC
Ini akan menghasilkan encrypted fail =mbsyncpass.gpg=. Simpan fail tersebut ke
=~/.emacs.d= dan buang fail sementara =.mbsyncpass= tadi.

Buat fail sementara =.authinfo= dan masukkan informasi ini
#+BEGIN_EXAMPLE
  machine imap.gmail.com login MyAccountName@gmail.com password MYPASSWORD
  machine smtp.gmail.com login MyAccountName@gmail.com password MYPASSWORD
#+END_EXAMPLE
Tukar yang berkenaan cth ~MyAccountName~ dan ~MYPASSWORD~

Kemudian untuk meng-encypt fail
#+BEGIN_SRC sh
  gpg2 --output ~/.authinfo.gpg --symmetric ~/.authinfo
#+END_SRC
Akan menghasilkan encrypted fail =.authoinfo.gpg=. Fail sementara =.authoinfo= boleh dibuang

* Aturcara isync utk Gmail

1. Berikan kebenaran ke [[https://support.google.com/accounts/answer/6010255?hl=en][Less Secure Apps]]
2. Pasangkan certificates yang diperlukan
   #+BEGIN_SRC sh
     sudo apt-get install ca-certificates
   #+END_SRC
3. Atur fail =~/.mbsyncrc= yang diperlukan.

** Contoh 1
   #+BEGIN_EXAMPLE
     IMAPAccount gmail
     # Address to connect to
     Host imap.gmail.com
     User yourname@gmail.com
     #Pass ***************
     # To store the password in an encrypted file use PassCmd instead of Pass
     #PassCmd "gpg2 -q --for-your-eyes-only --no-tty -d ~/.mbsyncpass.gpg"
     #
     # Use SSL
     UseIMAPS yes
     # The following line should work. If get certificate errors, uncomment the two following lines and read the "Troubleshooting" section.
     CertificateFile /etc/ssl/certs/ca-certificates.crt
     #CertificateFile ~/.cert/imap.gmail.com.pem
     #CertificateFile ~/.cert/Equifax_Secure_CA.pem

     IMAPStore gmail-remote
     Account gmail

     MaildirStore gmail-local
     # The trailing "/" is important
     Path ~/mail/
     Inbox ~/mail/Inbox

     Channel gmail
     Master :gmail-remote:
     Slave :gmail-local:
     # Exclude everything under the internal [Gmail] folder, except the interesting folders
     Patterns * ![Gmail]* "[Gmail]/Sent Mail" "[Gmail]/Starred" "[Gmail]/All Mail"
     # Or include everything
     #Patterns *
     # Automatically create missing mailboxes, both locally and on the server
     Create Both
     # Save the synchronization state files in the relevant directory
     SyncState *
   #+END_EXAMPLE
** Contoh 2
Contoh lain utk fail =.mbysncrc=
   #+BEGIN_EXAMPLE
     # ACCOUNT INFORMATION
     IMAPAccount gmail
     Host imap.gmail.com
     User MYEMAIL@gmail.com
     PassCmd "security find-generic-password -s mbsync-gmail-password -w"
     # UseIMAPS yes
     # AuthMechs LOGIN
     AuthMechs PLAIN
     SSLType IMAPS
     # SSLVersions SSLv3
     CertificateFile /usr/local/etc/openssl/certs/gmail.crt
     CertificateFile /usr/local/etc/openssl/certs/google.crt
     CertificateFile /usr/local/etc/openssl/certs/Equifax.crt

     # THEN WE SPECIFY THE LOCAL AND REMOTE STORAGE
     # - THE REMOTE STORAGE IS WHERE WE GET THE MAIL FROM (E.G., THE
     #   SPECIFICATION OF AN IMAP ACCOUNT)
     # - THE LOCAL STORAGE IS WHERE WE STORE THE EMAIL ON OUR COMPUTER

     # REMOTE STORAGE (USE THE IMAP ACCOUNT SPECIFIED ABOVE)
     IMAPStore gmail-remote
     Account gmail

     # LOCAL STORAGE (CREATE DIRECTORIES with mkdir -p Maildir/gmail)
     MaildirStore gmail-local
     Path ~/Maildir/gmail/
     Inbox ~/Maildir/gmail/inbox

     # CONNECTIONS SPECIFY LINKS BETWEEN REMOTE AND LOCAL FOLDERS
     #
     # CONNECTIONS ARE SPECIFIED USING PATTERNS, WHICH MATCH REMOTE MAIl
     # FOLDERS. SOME COMMONLY USED PATTERS INCLUDE:
     #
     # 1 "*" TO MATCH EVERYTHING
     # 2 "!DIR" TO EXCLUDE "DIR"
     # 3 "DIR" TO MATCH DIR
     #
     # FOR INSTANCE IN THE SPECIFICATION BELOW:
     #
     # gmail-inbox gets the folder INBOX, ARCHIVE, and everything under "ARCHIVE*"
     # gmail-trash gets only the "[Gmail]/Trash" folder and stores it to the local "trash" folder

     Channel gmail-inbox
     Master :gmail-remote:
     Slave :gmail-local:
     Patterns "INBOX" "Arch*"
     Create Both
     Expunge Both
     SyncState *

     Channel gmail-trash
     Master :gmail-remote:"[Gmail]/Trash"
     Slave :gmail-local:trash
     Create Both
     Expunge Both
     SyncState *

     Channel gmail-sent
     Master :gmail-remote:"[Gmail]/Sent Mail"
     Slave :gmail-local:sent
     Create Both
     Expunge Both
     SyncState *

     # GROUPS PUT TOGETHER CHANNELS, SO THAT WE CAN INVOKE
     # MBSYNC ON A GROUP TO SYNC ALL CHANNELS
     #
     # FOR INSTANCE: "mbsync gmail" GETS MAIL FROM
     # "gmail-inbox", "gmail-sent", and "gmail-trash"
     #
     Group gmail
     Channel gmail-inbox
     Channel gmail-sent
     Channel gmail-trash
   #+END_EXAMPLE

4. Utk sync email di server tertentu melalui terminal contohnya "work"
   #+BEGIN_SRC sh
     mbsync -c ~/.emacs.d/.mbsyncrc work
   #+END_SRC
